version: '3.9'
services:
  worker:
    container_name: worker
    build: .
    network_mode: host
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    # image: gcr.io/spank-me-botty/spank-me-botty
    restart: on-failure
